# Generated by Django 4.2.4 on 2023-08-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miler', '0003_alter_client_options_alter_deliveryattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='miler.client'),
        ),
    ]
