# Generated by Django 4.2.4 on 2023-08-28 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miler', '0004_alter_mailing_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogArticle',
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
